### ISSUE TITLE
Input data not found

### ISSUE THREAD

**Issue by awickert** [jacobzahn/FTCS_Model_Sol_Rad#1]
```
Traceback (most recent call last):
  File "model.py", line 10, in <module>
    data = pd.read_excel(fn, sheetname = sheet_title, header = 2)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 191, in read_excel
    io = ExcelFile(io, engine=engine)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 249, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/lib/python2.7/dist-packages/xlrd/__init__.py", line 395, in open_workbook
    with open(filename, "rb") as f:
IOError: [Errno 2] No such file or directory: 'ncomms14845-s3-2.xlsx'
```

**Comment by jacobzahn** [comment]
Forgot to load in excel file. Have corrected this.
